'use client';

import { useState } from 'react';
import Link from 'next/link';


export default function LandingPage() {
  const [form, setForm] = useState({ name: '', email: '', company: '', role: '', teamSize: '1-10' });
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setStatus('loading');
    try {
      const res = await fetch('/api/waitlist', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form)
      });
      if (res.ok) setStatus('success');
      else setStatus('error');
    } catch {
      setStatus('error');
    }
  };

  return (
    <div className="space-y-32">
      {/* Hero Section */}
      <section className="relative text-center space-y-8 pt-12">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[300px] bg-primary/20 blur-[120px] rounded-full -z-10" />
        
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-xs font-semibold text-primary mb-4 animate-slide-up">
           <span className="relative flex h-2 w-2">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
            <span className="relative inline-flex rounded-full h-2 w-2 bg-primary"></span>
          </span>
          Phase 1 Beta is Live
        </div>

        <h1 className="text-6xl md:text-8xl font-black tracking-tighter leading-none animate-slide-up [animation-delay:100ms]">
          The Proof of <br />
          <span className="bg-clip-text text-transparent bg-gradient-to-b from-primary to-primary-dark glow-text">Human</span> Intelligence
        </h1>
        
        <p className="text-xl text-white/60 max-w-2xl mx-auto leading-relaxed animate-slide-up [animation-delay:200ms]">
          MergeBrief analyzes your Pull Requests to detect AI code provenance, assess logic risk, and preserve human accountability in the loop.
        </p>

        <div className="flex flex-col sm:flex-row justify-center gap-4 animate-slide-up [animation-delay:300ms]">
          <Link href="/?demo=true" className="glass-button bg-primary/10 border-primary/50 text-white px-10 py-4 rounded-2xl font-bold hover:bg-primary transition shadow-[0_0_30px_rgba(59,130,246,0.3)]">
            Explore Interactive Demo
          </Link>
          <a href="#waitlist" className="glass-button px-10 py-4 rounded-2xl font-bold">
            Join the Waitlist
          </a>
        </div>

      </section>

      {/* Features Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 px-4">
        {[
          { 
            title: "AI Provenance", 
            desc: "Discover which parts of your PR were generated by AI tools via AST-level heuristics and metadata trailer detection.",
            icon: "🔍" 
          },
          { 
            title: "Risk Overlays", 
            desc: "Deterministic analysis of sensitive blast radius for high-risk modules like auth, infra, and database migrations.",
            icon: "🛡️" 
          },
          { 
            title: "Reviewer Context", 
            desc: "Attach human intent and 'why acceptable' merge notes to every AI-assisted change to maintain compliance.",
            icon: "✍️" 
          }
        ].map((feat, i) => (
          <div key={i} className="glass-card p-10 group hover:border-primary/50 transition-all duration-500 hover:-translate-y-2">
            <div className="text-4xl mb-6 transform group-hover:scale-110 transition-transform duration-500">{feat.icon}</div>
            <h3 className="font-bold text-2xl mb-4 text-white group-hover:text-primary transition-colors">{feat.title}</h3>
            <p className="text-white/50 leading-relaxed text-lg">{feat.desc}</p>
          </div>
        ))}
      </div>

      {/* Waitlist Section */}
      <section id="waitlist" className="relative group">
        <div className="absolute inset-0 bg-primary/5 blur-[100px] rounded-3xl -z-10 group-hover:bg-primary/10 transition-colors duration-1000" />
        <div className="glass-card p-12 md:p-20 overflow-hidden relative border-white/20">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            <div className="space-y-6">
              <h2 className="text-4xl md:text-5xl font-bold tracking-tight">Ready for the future of <span className="text-primary">PR reviews?</span></h2>
              <p className="text-lg text-white/50 leading-relaxed">
                We are onboarding 5 elite engineering teams each week to test the MergeBrief beta. Join our design partner program today.
              </p>
              <div className="flex items-center gap-6 pt-4 text-sm text-white/40">
                <div className="flex -space-x-3">
                  {[1, 2, 3, 4].map(j => (
                    <div key={j} className="w-10 h-10 rounded-full border-2 border-[#050810] bg-white/10 flex items-center justify-center font-bold">
                       {String.fromCharCode(64 + j)}
                    </div>
                  ))}
                </div>
                <p>Trusted by engineers at top-tier startups</p>
              </div>
            </div>
            
            <div className="bg-white/[0.02] border border-white/10 p-8 md:p-10 rounded-3xl shadow-2xl">
              {status === 'success' ? (
                <div className="text-center py-12 space-y-4 animate-fade-in">
                  <div className="w-20 h-20 bg-primary/20 text-primary rounded-full flex items-center justify-center mx-auto text-4xl mb-6 shadow-[0_0_40px_rgba(59,130,246,0.4)]">
                    ✓
                  </div>
                  <h3 className="text-3xl font-bold text-white">You're on the list!</h3>
                  <p className="text-white/60">We'll reach out shortly to discuss your engineering workflow.</p>
                </div>
              ) : (
                <form onSubmit={handleSubmit} className="space-y-6">
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div className="space-y-2">
                       <label className="text-xs font-semibold text-white/40 uppercase tracking-wider ml-1">Name</label>
                      <input 
                        type="text" required placeholder="Jane Doe" 
                        className="w-full bg-white/5 border-white/10 text-white rounded-xl px-4 py-3 focus:ring-2 focus:ring-primary focus:border-transparent transition-all outline-none" 
                        onChange={e => setForm({...form, name: e.target.value})}
                      />
                    </div>
                    <div className="space-y-2">
                       <label className="text-xs font-semibold text-white/40 uppercase tracking-wider ml-1">Email</label>
                      <input 
                        type="email" required placeholder="jane@company.com" 
                        className="w-full bg-white/5 border-white/10 text-white rounded-xl px-4 py-3 focus:ring-2 focus:ring-primary focus:border-transparent transition-all outline-none"
                        onChange={e => setForm({...form, email: e.target.value})}
                      />
                    </div>
                  </div>
                  <div className="space-y-2">
                     <label className="text-xs font-semibold text-white/40 uppercase tracking-wider ml-1">Company</label>
                    <input 
                      type="text" placeholder="Acme Inc." 
                      className="w-full bg-white/5 border-white/10 text-white rounded-xl px-4 py-3 focus:ring-2 focus:ring-primary focus:border-transparent transition-all outline-none"
                      onChange={e => setForm({...form, company: e.target.value})}
                    />
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div className="space-y-2">
                       <label className="text-xs font-semibold text-white/40 uppercase tracking-wider ml-1">Role</label>
                      <input 
                        type="text" placeholder="CTO / Lead Engineer" 
                        className="w-full bg-white/5 border-white/10 text-white rounded-xl px-4 py-3 focus:ring-2 focus:ring-primary focus:border-transparent transition-all outline-none"
                        onChange={e => setForm({...form, role: e.target.value})}
                      />
                    </div>
                    <div className="space-y-2">
                       <label className="text-xs font-semibold text-white/40 uppercase tracking-wider ml-1">Team Size</label>
                      <select 
                        className="w-full bg-white/5 border-white/10 text-white rounded-xl px-4 py-3 focus:ring-2 focus:ring-primary focus:border-transparent transition-all outline-none appearance-none"
                        onChange={e => setForm({...form, teamSize: e.target.value})}
                      >
                        <option value="1-10">1-10 engineers</option>
                        <option value="11-50">11-50 engineers</option>
                        <option value="51-200">51-200 engineers</option>
                        <option value="200+">200+ engineers</option>
                      </select>
                    </div>
                  </div>
                  <button 
                    type="submit" 
                    disabled={status === 'loading'}
                    className="w-full bg-primary hover:bg-primary-dark text-white py-4 rounded-xl font-bold transition-all disabled:opacity-50 shadow-[0_10px_30px_rgba(59,130,246,0.3)] hover:shadow-[0_15px_40px_rgba(59,130,246,0.4)]"
                  >
                    {status === 'loading' ? 'Submitting...' : 'Request Early Access'}
                  </button>
                  {status === 'error' && <p className="text-red-400 text-sm text-center">Oops! Something went wrong. Please try again.</p>}
                </form>
              )}
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
