'use client';

import { useState } from 'react';

export default function LandingPage() {
  const [form, setForm] = useState({ name: '', email: '', company: '', role: '', teamSize: '1-10' });
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setStatus('loading');
    try {
      const res = await fetch('/api/waitlist', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form)
      });
      if (res.ok) setStatus('success');
      else setStatus('error');
    } catch {
      setStatus('error');
    }
  };

  return (
    <div className="py-12 px-6 max-w-5xl mx-auto space-y-20">
      <section className="text-center space-y-6">
        <h1 className="text-5xl md:text-6xl font-extrabold tracking-tight text-gray-900">
          The Proof of <span className="text-blue-600">Human</span> Intelligence
        </h1>
        <p className="text-xl text-gray-600 max-w-2xl mx-auto">
          MergeBrief analyzes your Pull Requests to detect AI code provenance, assess risk, and preserve human accountability in the loop.
        </p>
        <div className="flex justify-center gap-4">
          <a href="#waitlist" className="bg-blue-600 text-white px-8 py-3 rounded-xl font-bold hover:bg-blue-700 transition shadow-lg">
            Join the Beta Waitlist
          </a>
          <a href="https://github.com/apps/merge-brief" className="bg-white border border-gray-200 px-8 py-3 rounded-xl font-bold hover:bg-gray-50 transition shadow-sm">
            View on GitHub
          </a>
        </div>
      </section>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        {[
          { title: "AI Provenance", desc: "Discover which parts of your PR were generated by AI tools via AST-level heuristics and trailer detection." },
          { title: "Risk Overlays", desc: "Deterministic analysis of blast radius for high-risk modules like auth, infra, and migrations." },
          { title: "Reviewer Flow", desc: "Attach human intent and 'why acceptable' merge notes to every AI-assisted change." }
        ].map((feat, i) => (
          <div key={i} className="p-8 bg-white border border-gray-100 rounded-2xl shadow-sm hover:shadow-md transition">
            <h3 className="font-bold text-xl mb-3 text-gray-900">{feat.title}</h3>
            <p className="text-gray-500 leading-relaxed">{feat.desc}</p>
          </div>
        ))}
      </div>

      <section id="waitlist" className="bg-gray-900 rounded-3xl p-8 md:p-12 text-white shadow-2xl">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold">Ready for the future of PR reviews?</h2>
            <p className="text-gray-400">Join our design partner waitlist. We are onboarding 5 teams each week to test the MergeBrief beta.</p>
          </div>
          
          {status === 'success' ? (
            <div className="bg-green-500/10 border border-green-500/20 p-8 rounded-2xl text-center">
              <h3 className="text-2xl font-bold text-green-400 mb-2">You're on the list!</h3>
              <p className="text-green-300">We'll reach out shortly to discuss your engineering workflow.</p>
            </div>
          ) : (
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <input 
                  type="text" required placeholder="Name" 
                  className="bg-gray-800 border-gray-700 text-white rounded-lg px-4 py-2 focus:ring-blue-500" 
                  onChange={e => setForm({...form, name: e.target.value})}
                />
                <input 
                  type="email" required placeholder="Email" 
                  className="bg-gray-800 border-gray-700 text-white rounded-lg px-4 py-2 focus:ring-blue-500"
                  onChange={e => setForm({...form, email: e.target.value})}
                />
              </div>
              <input 
                type="text" placeholder="Company Name" 
                className="bg-gray-800 border-gray-700 text-white rounded-lg w-full px-4 py-2 focus:ring-blue-500"
                onChange={e => setForm({...form, company: e.target.value})}
              />
              <div className="grid grid-cols-2 gap-4">
                <input 
                  type="text" placeholder="Your Role" 
                  className="bg-gray-800 border-gray-700 text-white rounded-lg px-4 py-2 focus:ring-blue-500"
                  onChange={e => setForm({...form, role: e.target.value})}
                />
                <select 
                  className="bg-gray-800 border-gray-700 text-white rounded-lg px-4 py-2 focus:ring-blue-500"
                  onChange={e => setForm({...form, teamSize: e.target.value})}
                >
                  <option>1-10 engineers</option>
                  <option>11-50 engineers</option>
                  <option>51-200 engineers</option>
                  <option>200+ engineers</option>
                </select>
              </div>
              <button 
                type="submit" 
                disabled={status === 'loading'}
                className="w-full bg-blue-600 hover:bg-blue-500 py-3 rounded-lg font-bold transition disabled:opacity-50"
              >
                {status === 'loading' ? 'Submitting...' : 'Request Early Access'}
              </button>
              {status === 'error' && <p className="text-red-400 text-sm">Oops! Something went wrong. Please try again.</p>}
            </form>
          )}
        </div>
      </section>
    </div>
  );
}
