import { analyzeCommitData } from '../src/core/detect.js';

describe('analyzeCommitData', () => {
  const sampleSha = 'a1b2c3d4';
  const sampleMessage = 'Add groundbreaking AI feature\n\nAI-generated-by: GPT-4';
  const sampleDiff = 'diff --git a/src/index.js b/src/index.js\n+ // AI generated code';
  const sampleNumstat = '10\t5\tsrc/index.js\n2\t0\tpackage.json';
  const sampleOctokitFiles = [
    { filename: 'src/index.js', additions: 10, deletions: 5 },
    { filename: 'package.json', additions: 2, deletions: 0 }
  ];

  it('should analyze data using numstat string (Git CLI style)', () => {
    const result = analyzeCommitData({
      sha: sampleSha,
      message: sampleMessage,
      diff: sampleDiff,
      files: sampleNumstat
    });

    expect(result).toEqual({
      sha: sampleSha,
      aiTool: 'GPT-4',
      confidence: 100,
      files: 2,
      linesAdded: 12,
      linesRemoved: 5,
      methods: ['trailer']
    });
  });

  it('should analyze data using files array (Octokit API style)', () => {
    const result = analyzeCommitData({
      sha: sampleSha,
      message: sampleMessage,
      diff: sampleDiff,
      files: sampleOctokitFiles
    });

    expect(result).toEqual({
      sha: sampleSha,
      aiTool: 'GPT-4',
      confidence: 100,
      files: 2,
      linesAdded: 12,
      linesRemoved: 5,
      methods: ['trailer']
    });
  });

  it('should detect AI via heuristics if trailer is missing', () => {
    const result = analyzeCommitData({
      sha: sampleSha,
      message: 'Just code',
      diff: 'Generated by Copilot\n+ some code',
      files: []
    });

    expect(result.aiTool).toBe('Unknown AI');
    expect(result.confidence).toBe(85);
    expect(result.methods).toContain('heuristic-explicit');
  });

  it('should return null aiTool if no fingerprints found', () => {
    const result = analyzeCommitData({
      sha: sampleSha,
      message: 'Boring commit',
      diff: '+ some code',
      files: []
    });

    expect(result.aiTool).toBeNull();
    expect(result.confidence).toBe(0);
    expect(result.methods).toHaveLength(0);
  });
});
