import { describe, it, expect } from '@jest/globals';
import { analyzeCommitData } from '../src/core/detect.js';

describe('analyzeCommitData (Enhanced)', () => {
  it('should detect explicit trailers with 100% confidence', () => {
    const result = analyzeCommitData({
      sha: 'test-sha',
      message: `Add feature

AI-generated-by: Claude`,
      diff: 'some code',
      files: '1	1	index.js'
    });
    expect(result.confidence).toBe(100);
    expect(result.aiTool).toBe('Claude');
    expect(result.methods).toContain('trailer');
  });

  it('should detect explicit heuristics with 85% confidence', () => {
    const result = analyzeCommitData({
      sha: 'test-sha',
      message: 'Fix bug',
      diff: `// AI-generated code
const x = 1;`,
      files: '1	0	index.js'
    });
    expect(result.confidence).toBe(85);
    expect(result.aiTool).toBe('Unknown AI');
    expect(result.methods).toContain('heuristic-explicit');
  });

  it('should detect model mentions in comments with 90% confidence', () => {
    const result = analyzeCommitData({
      sha: 'test-sha',
      message: 'Refactor',
      diff: `// Generated by ChatGPT
function test() {}`,
      files: '2	0	index.js'
    });
    expect(result.confidence).toBe(90);
    expect(result.methods).toContain('fingerprint:hallucinated-comment-metadata');
  });

  it('should combine multiple weak fingerprints', () => {
    const result = analyzeCommitData({
      sha: 'test-sha',
      message: 'Scaffold',
      diff: `// Add implementation here
/** @param {string} x @returns {number} */
class MyController {}`,
      files: '5	0	index.js'
    });
    // generic-placeholder (25) + excessive-jsdoc (15) + boilerplate-scaffold (10) = 50
    expect(result.confidence).toBe(50);
    expect(result.aiTool).toBe('Inferred AI');
    expect(result.methods).toContain('fingerprint:generic-placeholder');
    expect(result.methods).toContain('fingerprint:excessive-jsdoc');
    expect(result.methods).toContain('fingerprint:boilerplate-scaffold');
  });

  it('should cap semantic confidence at 90%', () => {
    const result = analyzeCommitData({
      sha: 'test-sha',
      message: 'Massive update',
      diff: `// Generated by LLM
// Add implementation here
/** @param {any} x */
class ServiceManager {}`,
      files: '10	0	index.js'
    });
    // metadata (90) + generic (25) + jsdoc (15) + boilerplate (10) = 140 -> capped at 90
    expect(result.confidence).toBe(90);
  });

  it('should return 0 confidence for human-looking code', () => {
    const result = analyzeCommitData({
      sha: 'test-sha',
      message: 'Simple fix',
      diff: 'const x = 1;',
      files: '1	1	index.js'
    });
    expect(result.confidence).toBe(0);
    expect(result.aiTool).toBeNull();
    expect(result.methods).toHaveLength(0);
  });
});
