const { getExecOutput } = require('@actions/exec');

async function getGitOutput(repoPath, args) {
  try {
    const { exitCode, stdout, stderr } = await getExecOutput('git', args, {
      cwd: repoPath,
      silent: true,
      ignoreReturnCode: true
    });
    
    if (exitCode !== 0) {
      throw new Error(`Git command failed with exit code ${exitCode}. Stderr: ${stderr}`);
    }
    
    return stdout.trim();
  } catch (error) {
    throw new Error(`Git execution error: ${error.message}`);
  }
}

async function analyzeCommit(repoPath, commitSha, trailerKey = 'AI-generated-by') {
  let aiTool = null;
  let confidence = 0;
  const methods = [];
  
  // 1. Check commit message for trailer
  const message = await getGitOutput(repoPath, ['show', '-s', '--format=%B', commitSha]);
  
  const trailerRegex = new RegExp(`^${trailerKey}:\\s*(.+)$`, 'im');
  const trailerMatch = message.match(trailerRegex);
  
  if (trailerMatch) {
    aiTool = trailerMatch[1].trim() || 'Unknown AI';
    confidence = 100;
    methods.push('trailer');
  } else {
    // 2. Heuristic check on git diff
    const diff = await getGitOutput(repoPath, ['show', commitSha]);
    const heuristicRegex = /(AI[\s-]?generated|Generated by Copilot|Written by AI|auto-generated by AI)/i;
    
    const heuristicMatch = diff.match(heuristicRegex);
    if (heuristicMatch) {
      aiTool = 'Unknown AI';
      confidence = 80;
      methods.push('heuristic');
    }
  }
  
  // 3. Count lines and files
  const numstat = await getGitOutput(repoPath, ['show', '--numstat', '--format=', commitSha]);
  
  let files = 0;
  let linesAdded = 0;
  let linesRemoved = 0;
  
  const statLines = numstat.split('\n').map(line => line.trim()).filter(line => line.length > 0);
  
  for (const line of statLines) {
    const parts = line.split(/\s+/);
    if (parts.length >= 3) {
      files++;
      const added = parseInt(parts[0], 10);
      const removed = parseInt(parts[1], 10);
      
      // Git represents binary file additions/deletions as "-" which parseInt parses as NaN
      if (!isNaN(added)) linesAdded += added;
      if (!isNaN(removed)) linesRemoved += removed;
    }
  }
  
  return {
    sha: commitSha,
    aiTool,
    confidence,
    files,
    linesAdded,
    linesRemoved,
    methods
  };
}

module.exports = {
  analyzeCommit
};
