import { getExecOutput } from '@actions/exec';
import { verifyAnalysis } from './verifier.js';

/**
 * Detection Engine Namespace
 * Groups all internal logic into a single object to ensure explicit binding 
 * and visibility in different ESM environments (like GitHub Action Node 20 runners).
 */
const engine = {
  /**
   * Semantic fingerprints of AI-generated code patterns.
   */
  SEMANTIC_FINGERPRINTS: [
    {
      name: 'generic-placeholder',
      pattern: /(\/\/|#)\s*(insert|add|your|implementation|logic|here|code|goes|here)/i,
      weight: 25,
      reason: 'Generic "add logic here" placeholders are common in AI-scaffolded code.'
    },
    {
      name: 'unusually-consistent-comments',
      pattern: /^(\s*(\/\/|#)\s*[A-Z].*[\.!?])\n\s*[a-z]/m,
      weight: 20,
      reason: 'AI often generates perfectly punctuated, sentence-case comments for every single block.'
    },
    {
      name: 'boilerplate-scaffold',
      pattern: /(class|function|const)\s+\w+(Controller|Service|Manager|Factory|Repository|Interface)/,
      weight: 10,
      reason: 'Heavy boilerplate names are common in AI-generated scaffolds.'
    },
    {
      name: 'excessive-jsdoc',
      pattern: /\/\*\*[\s\S]*?@param[\s\S]*?@returns[\s\S]*?\*\//g,
      weight: 15,
      reason: 'AI often generates exhaustive JSDoc for simple functions.'
    },
    {
      name: 'hallucinated-comment-metadata',
      pattern: /(\/\/|#)\s*(Generated by|Created by|Model:)\s*(ChatGPT|Claude|GPT|LLM|Ollama)/i,
      weight: 90,
      reason: 'Explicit model mentions in comments are high-confidence indicators.'
    },
    {
      name: 'perfect-punctuation-consistency',
      pattern: /^(?:(?:\+|-|\s)\s*(?:\/\/|#)\s*[A-Z][^.!?]*[.!?]\s*\n(?:\+|-|\s)\s*\w+)+/m,
      weight: 25,
      reason: 'Long sequences of perfectly punctuated comments followed by code are rare in raw human drafts but standard for LLMs.'
    }
  ],

  /**
   * Detects "pasted boilerplate" style by checking for high density of typical AI scaffolding names
   * relative to total unique identifiers in the diff.
   */
  calculateBoilerplateRatio: (diff) => {
    const keywords = ['Factory', 'Service', 'Controller', 'Manager', 'Repository', 'Interface', 'Adapter', 'Provider'];
    const identifiers = diff.match(/[A-Z][a-zA-Z0-9]{3,}/g) || [];
    if (identifiers.length < 3) return 0;

    let bpCount = 0;
    for (const id of identifiers) {
      if (keywords.some(kw => id.endsWith(kw))) {
        bpCount++;
      }
    }
    return bpCount / identifiers.length;
  },

  /**
   * Platform-agnostic commit analyzer
   */
  analyzeCommitData: ({ sha, message, diff, files, trailerKey = 'AI-generated-by' }) => {
    let aiTool = null;
    let confidence = 0;
    const methods = [];
    
    // 1. Check commit message for trailer (Highest Confidence)
    const trailerRegex = new RegExp(`^${trailerKey}:\\s*(.+)$`, 'im');
    const trailerMatch = message ? message.match(trailerRegex) : null;
    
    if (trailerMatch) {
      aiTool = trailerMatch[1].trim() || 'Unknown AI';
      confidence = 100;
      methods.push('trailer');
    } else if (diff) {
      // 2. Heuristic check on diff content
      const explicitHeuristicRegex = /(AI[\s-]?generated|Generated by Copilot|Written by AI|auto-generated by AI)/i;
      
      const heuristicMatch = diff.match(explicitHeuristicRegex);
      if (heuristicMatch) {
        aiTool = 'Unknown AI';
        confidence = 85;
        methods.push('heuristic-explicit');
      }

      // 3. Semantic Fingerprinting (Weak signals)
      if (confidence < 100) {
        let semanticScore = 0;
        for (const finger of engine.SEMANTIC_FINGERPRINTS) {
          if (finger.pattern.test(diff)) {
            semanticScore += finger.weight;
            methods.push(`fingerprint:${finger.name}`);
          }
        }
        
        const finalSemanticConfidence = Math.min(90, semanticScore);
        if (finalSemanticConfidence > confidence) {
          confidence = finalSemanticConfidence;
          if (!aiTool) aiTool = 'Inferred AI';
        }

        // 3.1 Structural Complexity / Boilerplate Density
        // If we see high density of "Textbook" names in a diff, bump confidence
        const boilerplateRatio = engine.calculateBoilerplateRatio(diff);
        if (boilerplateRatio > 0.15) {
          const bpConfidence = Math.min(60, Math.round(boilerplateRatio * 200));
          if (bpConfidence > confidence) {
            confidence = bpConfidence;
            methods.push('structure:high-boilerplate-ratio');
          }
        }
      }
    }
    
    // 4. Count lines and files
    let filesCount = 0;
    let linesAdded = 0;
    let linesRemoved = 0;

    if (Array.isArray(files)) {
      filesCount = files.length;
      for (const file of files) {
        linesAdded += (file.additions || 0);
        linesRemoved += (file.deletions || 0);
      }
    } else if (typeof files === 'string') {
      const statLines = files.split('\n').map(l => l.trim()).filter(l => l.length > 0);
      for (const line of statLines) {
        const parts = line.split(/\s+/);
        if (parts.length >= 3) {
          filesCount++;
          const added = parseInt(parts[0], 10);
          const removed = parseInt(parts[1], 10);
          if (!isNaN(added)) linesAdded += added;
          if (!isNaN(removed)) linesRemoved += removed;
        }
      }
    }
    
    return { sha, aiTool, confidence, files: filesCount, linesAdded, linesRemoved, methods };
  },

  /**
   * Internal Git Wrapper
   */
  getGitOutput: async (repoPath, args) => {
    try {
      const { exitCode, stdout, stderr } = await getExecOutput('git', args, {
        cwd: repoPath,
        silent: true,
        ignoreReturnCode: true
      });
      
      if (exitCode !== 0) {
        throw new Error(`Git command failed with exit code ${exitCode}. Stderr: ${stderr}`);
      }
      return stdout.trim();
    } catch (error) {
      throw new Error(`Git execution error: ${error.message}`);
    }
  },

  /**
   * Main Analyzer Entry Point
   */
  analyzeCommit: async (repoPath, commitSha, trailerKey = 'AI-generated-by') => {
    // 0. Check for shallow clone
    const isShallowStr = await engine.getGitOutput(repoPath, ['rev-parse', '--is-shallow-repository']);
    if (isShallowStr === 'true') {
      throw new Error('Shallow repository checkout detected. Please set fetch-depth: 0 in your checkout step.');
    }

    // 1. Fetch data via git
    const message = await engine.getGitOutput(repoPath, ['show', '-s', '--format=%B', commitSha]);
    const diff = await engine.getGitOutput(repoPath, ['show', commitSha]);
    const numstat = await engine.getGitOutput(repoPath, ['show', '--numstat', '--format=', commitSha]);

    const analysis = engine.analyzeCommitData({
      sha: commitSha,
      message,
      diff,
      files: numstat,
      trailerKey
    });

    // 3. Optional LLM Verification for inferred results
    return await verifyAnalysis(diff, analysis);
  }
};

// Top-level exports for backward compatibility
export const getGitOutput = engine.getGitOutput;
export const SEMANTIC_FINGERPRINTS = engine.SEMANTIC_FINGERPRINTS;
export const analyzeCommitData = engine.analyzeCommitData;
export const analyzeCommit = engine.analyzeCommit;

export default engine;
