import { getExecOutput } from '@actions/exec';

export async function getGitOutput(repoPath, args) {
  try {
    const { exitCode, stdout, stderr } = await getExecOutput('git', args, {
      cwd: repoPath,
      silent: true,
      ignoreReturnCode: true
    });
    
    if (exitCode !== 0) {
      throw new Error(`Git command failed with exit code ${exitCode}. Stderr: ${stderr}`);
    }
    
    return stdout.trim();
  } catch (error) {
    throw new Error(`Git execution error: ${error.message}`);
  }
}

/**
 * Semantic fingerprints of AI-generated code patterns.
 * These are "weak signals" that, when combined, increase confidence.
 */
export const SEMANTIC_FINGERPRINTS = [
  {
    name: 'generic-placeholder',
    pattern: /(\/\/|#)\s*(insert|add|your|implementation|logic|here|code|goes|here)/i,
    weight: 25,
    reason: 'Generic "add logic here" placeholders are common in AI-scaffolded code.'
  },
  {
    name: 'unusually-consistent-comments',
    pattern: /^(\s*(\/\/|#)\s*[A-Z].*[\.!?])\n\s*[a-z]/m,
    weight: 20,
    reason: 'AI often generates perfectly punctuated, sentence-case comments for every single block.'
  },
  {
    name: 'boilerplate-scaffold',
    pattern: /(class|function|const)\s+\w+(Controller|Service|Manager|Factory|Repository|Interface)/,
    weight: 10, // Very weak on its own
    reason: 'Heavy boilerplate names are common in AI-generated scaffolds.'
  },
  {
    name: 'excessive-jsdoc',
    pattern: /\/\*\*[\s\S]*?@param[\s\S]*?@returns[\s\S]*?\*\//g,
    weight: 15,
    reason: 'AI often generates exhaustive JSDoc for simple functions.'
  },
  {
    name: 'hallucinated-comment-metadata',
    pattern: /(\/\/|#)\s*(Generated by|Created by|Model:)\s*(ChatGPT|Claude|GPT|LLM|Ollama)/i,
    weight: 90,
    reason: 'Explicit model mentions in comments are high-confidence indicators.'
  }
];

/**
 * Platform-agnostic commit analyzer
 * @param {Object} data 
 * @param {string} data.sha
 * @param {string} data.message
 * @param {string} data.diff
 * @param {string|Array} data.files - Either numstat string or array of file objects {additions, deletions}
 * @param {string} data.trailerKey
 */
export function analyzeCommitData({ sha, message, diff, files, trailerKey = 'AI-generated-by' }) {
  let aiTool = null;
  let confidence = 0;
  const methods = [];
  
  // 1. Check commit message for trailer (Highest Confidence)
  const trailerRegex = new RegExp(`^${trailerKey}:\\s*(.+)$`, 'im');
  const trailerMatch = message.match(trailerRegex);
  
  if (trailerMatch) {
    aiTool = trailerMatch[1].trim() || 'Unknown AI';
    confidence = 100;
    methods.push('trailer');
  } else {
    // 2. Heuristic check on diff content
    const explicitHeuristicRegex = /(AI[\s-]?generated|Generated by Copilot|Written by AI|auto-generated by AI)/i;
    
    if (diff) {
      const heuristicMatch = diff.match(explicitHeuristicRegex);
      if (heuristicMatch) {
        aiTool = 'Unknown AI';
        confidence = 85;
        methods.push('heuristic-explicit');
      }

      // 3. Semantic Fingerprinting (Weak signals)
      if (confidence < 100) {
        let semanticScore = 0;
        for (const finger of SEMANTIC_FINGERPRINTS) {
          if (finger.pattern.test(diff)) {
            semanticScore += finger.weight;
            methods.push(`fingerprint:${finger.name}`);
          }
        }
        
        // Cap semantic confidence at 90 unless explicit trailer found
        const finalSemanticConfidence = Math.min(90, semanticScore);
        if (finalSemanticConfidence > confidence) {
          confidence = finalSemanticConfidence;
          if (!aiTool) aiTool = 'Inferred AI';
        }
      }
    }
  }
  
  // 4. Count lines and files
  let filesCount = 0;
  let linesAdded = 0;
  let linesRemoved = 0;

  if (Array.isArray(files)) {
    // Octokit files format
    filesCount = files.length;
    for (const file of files) {
      linesAdded += (file.additions || 0);
      linesRemoved += (file.deletions || 0);
    }
  } else if (typeof files === 'string') {
    // Numstat string format
    const statLines = files.split('\n').map(line => line.trim()).filter(line => line.length > 0);
    for (const line of statLines) {
      const parts = line.split(/\s+/);
      if (parts.length >= 3) {
        filesCount++;
        const added = parseInt(parts[0], 10);
        const removed = parseInt(parts[1], 10);
        if (!isNaN(added)) linesAdded += added;
        if (!isNaN(removed)) linesRemoved += removed;
      }
    }
  }
  
  return {
    sha,
    aiTool,
    confidence,
    files: filesCount,
    linesAdded,
    linesRemoved,
    methods
  };
}

export async function analyzeCommit(repoPath, commitSha, trailerKey = 'AI-generated-by') {
  // 0. Check for shallow clone
  const isShallowStr = await getGitOutput(repoPath, ['rev-parse', '--is-shallow-repository']);
  if (isShallowStr === 'true') {
    throw new Error('Shallow repository checkout detected. Please set fetch-depth: 0 in your checkout step.');
  }

  // 1. Fetch data via git
  const message = await getGitOutput(repoPath, ['show', '-s', '--format=%B', commitSha]);
  const diff = await getGitOutput(repoPath, ['show', commitSha]);
  const numstat = await getGitOutput(repoPath, ['show', '--numstat', '--format=', commitSha]);

  // 2. Analyze using the core data processor
  return analyzeCommitData({
    sha: commitSha,
    message,
    diff,
    files: numstat,
    trailerKey
  });
}


