const { Anthropic } = require('@anthropic-ai/sdk');

/**
 * Analyzes a git diff using Claude to determine semantic intent and risk areas.
 */
async function analyzeDiffIntent(diff, provenanceSummary) {
  if (!process.env.ANTHROPIC_API_KEY) {
    console.warn('[LLM] ANTHROPIC_API_KEY not found, skipping semantic analysis.');
    return null;
  }

  const anthropic = new Anthropic({
    apiKey: process.env.ANTHROPIC_API_KEY,
  });

  const systemPrompt = `
You are an expert technical lead and security reviewer.
Analyze the provided git diff and AI provenance analysis results.
The provenance results indicate which parts of the code were likely generated by AI.

Your goal is to summarize the changes so a human reviewer knows exactly what is being changed and where the risks are.

Provide your analysis in the following JSON format:
{
  "intents": ["String summary of intent 1", "String summary of intent 2"],
  "blastRadius": ["Area 1 (e.g. Auth, DB, UI)", "Area 2"],
  "highRiskFiles": ["Specific file path or glob pattern (e.g. src/auth/*)"]
}

Keep descriptions concise and technical. Focus on the 'Blast Radius'.
`;

  const userMessage = `
AI Provenance Findings:
${JSON.stringify(provenanceSummary, null, 2)}

Git Diff:
${diff.substring(0, 30000)} // Truncate if too long
`;

  try {
    const response = await anthropic.messages.create({
      model: "claude-3-5-sonnet-20240620",
      max_tokens: 1024,
      system: systemPrompt,
      messages: [
        { role: "user", content: userMessage }
      ],
    });

    const content = response.content[0].text;
    return JSON.parse(content);
  } catch (error) {
    console.error(`[LLM] Error calling Anthropic: ${error.message}`);
    return null;
  }
}

module.exports = {
  analyzeDiffIntent
};
